url: https://aossie.gitlab.io
baseurl: 

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - node_modules
  - gulpfile.js
  - package.json

# Site settings
title: AOSSIE
email: aossie-gsoc-2017@googlegroups.com
description: "Australian Open-Source Software Innovation and Education"


# Team names, titles and social links
people:
- name: Bruno Woltzenlogel Paleo
  pic: 1
  position: Org-Admin
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Ekaterina Lebedeva
  pic: 2
  position: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Chirag Arora
  pic: 3
  position: 
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Ideas
ideas:
- project: Agora
  title: More Algorithms
  id: 1
  description: agora-algorithms.md
- project: Agora
  title: Web Front-End
  id: 2
  description: agora-web.md
- project: Carbon Footprint
  title: Mobile App
  id: 3
  description: footprint-mobile.md
- project: Carbon Footprint
  title: Footprint for Flights
  id: 4
  description: footprint-flights.md
- project: Carbon Footprint
  title: API
  id: 5
  description: footprint-api.md
- project: Carbon Footprint
  title: WebExtensions
  id: 6
  description: footprint-webext.md
- project: Carbon Footprint
  title: macOS App
  id: 7
  description: footprint-macOS.md
- project: Computational Philosophy
  title: Ontological Arguments
  id: 8
  description: philosophy-ontological.md
- project: Mind The Word
  title: Firefox and Safari Ports
  id: 9
  description: mtw-ports.md
- project: Mind The Word
  title: Mobile App
  id: 10
  description: mtw-mobile.md
- project: Scavenger
  title: Equality Reasoning
  id: 11
  description: scavenger-equality.md
- project: Scavenger
  title: Parallel Theorem Proving
  id: 12
  description: scavenger-parallel.md
- project: Scavenger
  title: Search Improvements
  id: 13
  description: scavenger-improvements.md
- project: Skeptik
  title: Interpolation
  id: 14
  description: skeptik-interpolation.md
- project: Skeptik
  title: Boosting Performance!
  id: 15
  description: skeptik-performance.md



# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
#  - title: twitter
#    url: http://twitter.com/jekyllrb
#  - title: facebook
#    url:
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
#  - title: bitbucket 
#    url: http://bitbucket.org/jekyll
  - title: github
    url: http://www.gitlab.com/aossie
  - title: google-plus
    url: https://groups.google.com/forum/#!forum/aossie-gsoc-2017

# Postal address (add as many lines as necessary)
address:
  - line: Canberra
  - line: Australia

# Build settings
markdown: kramdown
permalink: pretty
